version: '3.8'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=${REDIS_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo_db
      - redis_cache

  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - '27017:27017'

  redis_cache:
    image: redis
    container_name: redis_cache
    ports:
      - '6379:6379'
